#!/bin/bash

#  Copyright 2009, 2010 Alexander Batischev

#  This file is part of Trashman.

#  Trashman is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  Trashman is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.

#  You can read a copy of the GNU General Public License in the COPYING file
#  distributed with Trashman or at <http://www.gnu.org/licenses/>.


# findcd - searches for files in the database
#
# USAGE: findcd request
# request is a single word or regular expression

# database location
db="$HOME/.trashman.db"

request="$1"
if [ -z "$request" ]
then
    echo "USAGE: findcd request"
    echo "request can be a single word or regular expression. By default, case ignored"
    exit
fi
 
bunzip2 --stdout "$db" | awk '
BEGIN {
    isDiscNamePrinted = 0
}

/^===/ {
    discName = substr($0,4)
    isDiscNamePrinted = 0
    next
}

match(tolower($0), tolower("'$request'")) {
    if ( isDiscNamePrinted == 0 ) {
        print "\nDisc \""discName"\""
        isDiscNamePrinted = 1
    }
    print "\t", $0
}
'
