#!/bin/bash

#  Copyright 2009, 2010 Alexander Batischev

#  This file is part of Trashman.

#  Trashman is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  Trashman is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.

#  You can read a copy of the GNU General Public License in the COPYING file
#  distributed with Trashman or at <http://www.gnu.org/licenses/>.


# listcd - lists names of already added storade devices

# database location
db="$HOME/.trashman.db"

bunzip2 --stdout "$db" | grep '===' | sed 's/===//'
